# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python bot reminder

on:
  schedule:
    - cron: '*/5 0-15 * * *' # Every 30 minutes, between 07:00 AM and 09:59 PM (converted to UTC)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Execute py script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
        CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
      run: python main.py
